image: docker:dind
services:
    - docker:dind

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:latest
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  CONTAINER_STABLE_IMAGE: $CI_REGISTRY_IMAGE:stable

.buildcontainers: &buildcontainers
  - docker build --pull --target httpd-php -t fpfis/httpd-php:$PHP_VERSION .
  - docker push

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_74:
  stage: build
  variables:
    PHP_VERSION: "7.4"
  script:
    *buildcontainers