image: docker:dind
services:
    - docker:dind

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:latest
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  CONTAINER_STABLE_IMAGE: $CI_REGISTRY_IMAGE:stable

stages:
    - build


.buildcontainers: &buildcontainers
  - docker images
  - docker ps
  - docker build --pull --build-arg php_version=$PHP_VERSION --target httpd-php -t fpfis/httpd-php:$PHP_VERSION -t $CI_REGISTRY/fpfis/httpd-php:$PHP_VERSION .
  - docker push $CI_REGISTRY/fpfis/httpd-php:$PHP_VERSION

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY



build_56:
  stage: build
  variables:
    PHP_VERSION: "5.6"
  script:
    *buildcontainers

build_71:
  stage: build
  variables:
    PHP_VERSION: "7.1"
  script:
    *buildcontainers

build_72:
  stage: build
  variables:
    PHP_VERSION: "7.2"
  script:
    *buildcontainers

build_73:
  stage: build
  variables:
    PHP_VERSION: "7.3"
  script:
    *buildcontainers

build_74:
  stage: build
  variables:
    PHP_VERSION: "7.4"
  script:
    *buildcontainers

