image: docker:dind
services:
    - docker:dind

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:latest
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  CONTAINER_STABLE_IMAGE: $CI_REGISTRY_IMAGE:stable

.php56: &php56
  PHP_VERSION: "5.6"
.php71: &php71
  PHP_VERSION: "7.1"
.php72: &php72
  PHP_VERSION: "7.2"
.php73: &php73
  PHP_VERSION: "7.3"
.php74: &php74
  PHP_VERSION: "7.1"
            
.oci20: &oci20
  OCI8_VERSION: "2.0.12"
.oci21: &oci21
  OCI8_VERSION: "2.1.8"
.oci22: &oci22
  OCI8_VERSION: "2.2.0"

.fullimage: &fullimage
  IMAGE: "-full"
.ciimage: &ciimage
  IMAGE: "-ci"
.devimage: &devimage
  IMAGE: "-dev"
.ociimage: &ociimage
  IMAGE: "-oci"
.ocidevimage: &ocidevimage
  IMAGE: "-oci-dev"

stages:
    - base
    - full
    - ci
    - dev
    - oci
    - oci-dev


.buildscript: &buildscript
  - docker build --pull --build-arg php_version=$PHP_VERSION --build-arg oci8_version=$OCI8_VERSION --target httpd-php$IMAGE -t fpfis/httpd-php$IMAGE:$PHP_VERSION -t $CI_REGISTRY/fpfis/httpd-php:$PHP_VERSION$IMAGE .
  - docker push $CI_REGISTRY/fpfis/$IMAGE:$PHP_VERSION

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

base:56:
  stage: base
  variables:
    <<: *php56
  script:
    *buildscript

base:71:
  stage: base
  variables:
    <<: *php71
  script:
    *buildscript

base:72:
  stage: base
  variables:
    <<: *php72
  script:
    *buildscript

base:73:
  stage: base
  variables:
    <<: *php73
  script:
    *buildscript

base:74:
  stage: base
  variables:
    <<: *php74
  script:
    *buildscript

full:56:
  stage: full
  variables:
    <<: [ *php56, *fullimage ]
  script:
    *buildscript
  dependencies:
    - base:56

full:71:
  stage: full
  variables:
    <<: [ *php71, *fullimage ]
  script:
    *buildscript
  dependencies:
    - base:71

full:72:
  stage: full
  variables:
    <<: [ *php72, *fullimage ]
  script:
    *buildscript
  dependencies:
    - base:72

full:73:
  stage: full
  variables:
    <<: [ *php73, *fullimage ]
  script:
    *buildscript
  dependencies:
    - base:73

full:74:
  stage: full
  variables:
    <<: [ *php74, *fullimage ]
  script:
    *buildscript
  dependencies:
    - base:74