image: docker:dind
services:
    - docker:dind

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:latest
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  CONTAINER_STABLE_IMAGE: $CI_REGISTRY_IMAGE:stable

.php56: &php56
  PHP_VERSION: "5.6"
.php71: &php71
  PHP_VERSION: "7.1"
.php72: &php72
  PHP_VERSION: "7.2"
.php73: &php73
  PHP_VERSION: "7.3"
.php74: &php74
  PHP_VERSION: "7.4"
            
.oci20: &oci20
  OCI8_VERSION: "2.0.12"
.oci21: &oci21
  OCI8_VERSION: "2.1.8"
.oci22: &oci22
  OCI8_VERSION: "2.2.0"

.fullimage: &fullimage
  IMAGE: "-full"
.ciimage: &ciimage
  IMAGE: "-ci"
.devimage: &devimage
  IMAGE: "-dev"
.ociimage: &ociimage
  IMAGE: "-oci"
.ocidevimage: &ocidevimage
  IMAGE: "-oci-dev"

stages:
    - base
    - full
    - ci
    - dev
    - oci
    - ocidev


.buildscript: &buildscript
  - docker build --pull --build-arg php_version=$PHP_VERSION --build-arg oci8_version=$OCI8_VERSION --target httpd-php$IMAGE -t fpfis/httpd-php$IMAGE:$PHP_VERSION -t $CI_REGISTRY/fpfis/httpd-php:$PHP_VERSION$IMAGE -t fpfis/httpd-php:$PHP_VERSION$IMAGE .
  - docker push $CI_REGISTRY/fpfis/httpd-php:$PHP_VERSION$IMAGE
  - docker push fpfis/httpd-php$IMAGE:$PHP_VERSION
  - docker push fpfis/httpd-php:$PHP_VERSION$IMAGE

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $dockerio_user -p $dockerio_password

#####
# Base
#####
base:56:
  stage: base
  variables:
    <<: *php56
  script:
    *buildscript

base:71:
  stage: base
  variables:
    <<: *php71
  script:
    *buildscript

base:72:
  stage: base
  variables:
    <<: *php72
  script:
    *buildscript

base:73:
  stage: base
  variables:
    <<: *php73
  script:
    *buildscript

base:74:
  stage: base
  variables:
    <<: *php74
  script:
    *buildscript

#####
# Full
#####
full:56:
  stage: full
  variables:
    <<: [ *php56, *fullimage ]
  script:
    *buildscript
  needs: ["base:56"]

full:71:
  stage: full
  variables:
    <<: [ *php71, *fullimage ]
  script:
    *buildscript
  needs: ["base:71"]

full:72:
  stage: full
  variables:
    <<: [ *php72, *fullimage ]
  script:
    *buildscript
  needs: ["base:72"]

full:73:
  stage: full
  variables:
    <<: [ *php73, *fullimage ]
  script:
    *buildscript
  needs: ["base:73"]

full:74:
  stage: full
  variables:
    <<: [ *php74, *fullimage ]
  script:
    *buildscript
  needs: ["base:74"]

#####
# CI
#####
ci:56:
  stage: ci
  variables:
    <<: [ *php56, *ciimage ]
  script:
    *buildscript
  needs: ["full:56"]

ci:71:
  stage: ci
  variables:
    <<: [ *php71, *ciimage ]
  script:
    *buildscript
  needs: ["full:71"]

ci:72:
  stage: ci
  variables:
    <<: [ *php72, *ciimage ]
  script:
    *buildscript
  needs: ["full:72"]

ci:73:
  stage: ci
  variables:
    <<: [ *php73, *ciimage ]
  script:
    *buildscript
  needs: ["full:73"]

ci:74:
  stage: ci
  variables:
    <<: [ *php74, *ciimage ]
  script:
    *buildscript
  needs: ["full:74"]

#####
# Dev
#####
dev:56:
  stage: dev
  variables:
    <<: [ *php56, *devimage ]
  script:
    *buildscript
  needs: ["ci:56"]

dev:71:
  stage: dev
  variables:
    <<: [ *php71, *devimage ]
  script:
    *buildscript
  needs: ["ci:71"]

dev:72:
  stage: dev
  variables:
    <<: [ *php72, *devimage ]
  script:
    *buildscript
  needs: ["ci:72"]

dev:73:
  stage: dev
  variables:
    <<: [ *php73, *devimage ]
  script:
    *buildscript
  needs: ["ci:73"]

dev:74:
  stage: dev
  variables:
    <<: [ *php74, *devimage ]
  script:
    *buildscript
  needs: ["ci:74"]

#####
# OCI
#####
oci:56:
  stage: oci
  variables:
    <<: [ *php56, *ociimage, *oci20 ]
  script:
    *buildscript
  needs: ["full:56"]

oci:71:
  stage: oci
  variables:
    <<: [ *php71, *ociimage, *oci21 ]
  script:
    *buildscript
  needs: ["full:71"]

oci:72:
  stage: oci
  variables:
    <<: [ *php72, *ociimage, *oci22 ]
  script:
    *buildscript
  needs: ["full:72"]

oci:73:
  stage: oci
  variables:
    <<: [ *php73, *ociimage, *oci22 ]
  script:
    *buildscript
  needs: ["full:73"]

oci:74:
  stage: oci
  variables:
    <<: [ *php74, *ociimage, *oci22 ]
  script:
    *buildscript
  needs: ["full:74"]

#####
# OCI-DEV
#####
ocidev:56:
  stage: ocidev
  variables:
    <<: [ *php56, *ocidevimage, *oci20 ]
  script:
    *buildscript
  needs: ["dev:56"]

ocidev:71:
  stage: ocidev
  variables:
    <<: [ *php71, *ocidevimage, *oci21 ]
  script:
    *buildscript
  needs: ["dev:71"]

ocidev:72:
  stage: ocidev
  variables:
    <<: [ *php72, *ocidevimage, *oci22 ]
  script:
    *buildscript
  needs: ["dev:72"]

ocidev:73:
  stage: ocidev
  variables:
    <<: [ *php73, *ocidevimage, *oci22 ]
  script:
    *buildscript
  needs: ["dev:73"]

ocidev:74:
  stage: ocidev
  variables:
    <<: [ *php74, *ocidevimage, *oci22 ]
  script:
    *buildscript
  needs: ["dev:74"]